name: Deploy Production

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 9

            -   name: Install dependencies
                run: pnpm install --frozen-lockfile

            -   name: Build project
                run: NODE_ENV=production pnpm run build

            -   name: Upload production-ready build files
                uses: actions/upload-artifact@v4
                with:
                    name: production-files
                    path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 9

            -   name: Download artifact
                uses: actions/download-artifact@v4
                with:
                    name: production-files
                    path: ./dist

            -   name: Install Vercel CLI
                run: npm install -g vercel@latest

            -   name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            -   name: Install dependencies
                run: pnpm install --frozen-lockfile

            -   name: Build Project Artifacts
                run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            -   name: Deploy Project Artifacts to Vercel
                run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
